#!/usr/bin/env python

import sys, os
from libhippo import repo


def main():
    from optparse import OptionParser

    epi = "Supported commands: %s"%(", ".join(sorted(repo.COMMANDS)))

    parser = OptionParser(
        usage="%prog cmd [options]",
        epilog = epi
    )
    parser.add_option(
        "", "--hippodir", dest="hippodir",
        help="Hippo directory (/var/hippo)", metavar="DIR",
        default = repo.HIPPO_DIR
    )
    parser.add_option(
        "", "--base", dest="base",
        help="Host base (/)", metavar="DIR",
        default = repo.HIPPO_BASE
    )

    subcommand = None
    for i in sys.argv:
        if i in repo.COMMANDS:
            subcommand = sys.argv.index(i)
            
    (options, args) = parser.parse_args(sys.argv[1:subcommand or len(sys.argv)])

    r = repo.Hippo(os.path.abspath(options.hippodir), os.path.abspath(options.base))
    if subcommand:
        getattr(r, sys.argv[subcommand])(sys.argv[subcommand+1:])
    else:
        parser.error("Please pass a command.")

    
if __name__ == "__main__":
    main()
